
modLoader="kotlinforforge"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/bms-1984/Triad/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://github.com/bms-1984/Triad/raw/main/update.json"
displayURL="https://github.com/bms-1984/Triad"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="kotlinforforge"
    type="required"
    versionRange="${kotlinforforge_version_range}"
    ordering="NONE"
    side="BOTH"
